INSERT INTO `countries` (`id`, `name_spanish`, `name`, `iso2`, `iso3`, `phone_code`, `created_at`, `updated_at`) VALUES
                                                                                                                     (1, 'Afganistán', 'Afghanistan', 'AF', 'AFG', '93', NULL, NULL),
                                                                                                                     (2, 'Albania', 'Albania', 'AL', 'ALB', '355', NULL, NULL),
                                                                                                                     (3, 'Alemania', 'Germany', 'DE', 'DEU', '49', NULL, NULL),
                                                                                                                     (4, 'Andorra', 'Andorra', 'AD', 'AND', '376', NULL, NULL),
                                                                                                                     (5, 'Angola', 'Angola', 'AO', 'AGO', '244', NULL, NULL),
                                                                                                                     (6, 'Anguila', 'Anguilla', 'AI', 'AIA', '1 26', NULL, NULL),
                                                                                                                     (7, 'Antártida', 'Antarctica', 'AQ', 'ATA', '672', NULL, NULL),
                                                                                                                     (8, 'Antigua y Barbuda', 'Antigua and Barbuda', 'AG', 'ATG', '1 26', NULL, NULL),
                                                                                                                     (9, 'Arabia Saudita', 'Saudi Arabia', 'SA', 'SAU', '966', NULL, NULL),
                                                                                                                     (10, 'Argelia', 'Algeria', 'DZ', 'DZA', '213', NULL, NULL),
                                                                                                                     (11, 'Argentina', 'Argentina', 'AR', 'ARG', '54', NULL, NULL),
                                                                                                                     (12, 'Armenia', 'Armenia', 'AM', 'ARM', '374', NULL, NULL),
                                                                                                                     (13, 'Aruba', 'Aruba', 'AW', 'ABW', '297', NULL, NULL),
                                                                                                                     (14, 'Australia', 'Australia', 'AU', 'AUS', '61', NULL, NULL),
                                                                                                                     (15, 'Austria', 'Austria', 'AT', 'AUT', '43', NULL, NULL),
                                                                                                                     (16, 'Azerbaiyán', 'Azerbaijan', 'AZ', 'AZE', '994', NULL, NULL),
                                                                                                                     (17, 'Bélgica', 'Belgium', 'BE', 'BEL', '32', NULL, NULL),
                                                                                                                     (18, 'Bahamas', 'Bahamas', 'BS', 'BHS', '1 24', NULL, NULL),
                                                                                                                     (19, 'Bahrein', 'Bahrain', 'BH', 'BHR', '973', NULL, NULL),
                                                                                                                     (20, 'Bangladesh', 'Bangladesh', 'BD', 'BGD', '880', NULL, NULL),
                                                                                                                     (21, 'Barbados', 'Barbados', 'BB', 'BRB', '1 24', NULL, NULL),
                                                                                                                     (22, 'Belice', 'Belize', 'BZ', 'BLZ', '501', NULL, NULL),
                                                                                                                     (23, 'Benín', 'Benin', 'BJ', 'BEN', '229', NULL, NULL),
                                                                                                                     (24, 'Bhután', 'Bhutan', 'BT', 'BTN', '975', NULL, NULL),
                                                                                                                     (25, 'Bielorrusia', 'Belarus', 'BY', 'BLR', '375', NULL, NULL),
                                                                                                                     (26, 'Birmania', 'Myanmar', 'MM', 'MMR', '95', NULL, NULL),
                                                                                                                     (27, 'Bolivia', 'Bolivia', 'BO', 'BOL', '591', NULL, NULL),
                                                                                                                     (28, 'Bosnia y Herzegovina', 'Bosnia and Herzegovi', 'BA', 'BIH', '387', NULL, NULL),
                                                                                                                     (29, 'Botsuana', 'Botswana', 'BW', 'BWA', '267', NULL, NULL),
                                                                                                                     (30, 'Brasil', 'Brazil', 'BR', 'BRA', '55', NULL, NULL),
                                                                                                                     (31, 'Brunéi', 'Brunei', 'BN', 'BRN', '673', NULL, NULL),
                                                                                                                     (32, 'Bulgaria', 'Bulgaria', 'BG', 'BGR', '359', NULL, NULL),
                                                                                                                     (33, 'Burkina Faso', 'Burkina Faso', 'BF', 'BFA', '226', NULL, NULL),
                                                                                                                     (34, 'Burundi', 'Burundi', 'BI', 'BDI', '257', NULL, NULL),
                                                                                                                     (35, 'Cabo Verde', 'Cape Verde', 'CV', 'CPV', '238', NULL, NULL),
                                                                                                                     (36, 'Camboya', 'Cambodia', 'KH', 'KHM', '855', NULL, NULL),
                                                                                                                     (37, 'Camerún', 'Cameroon', 'CM', 'CMR', '237', NULL, NULL),
                                                                                                                     (38, 'Canadá', 'Canada', 'CA', 'CAN', '1', NULL, NULL),
                                                                                                                     (39, 'Chad', 'Chad', 'TD', 'TCD', '235', NULL, NULL),
                                                                                                                     (40, 'Chile', 'Chile', 'CL', 'CHL', '56', NULL, NULL),
                                                                                                                     (41, 'China', 'China', 'CN', 'CHN', '86', NULL, NULL),
                                                                                                                     (42, 'Chipre', 'Cyprus', 'CY', 'CYP', '357', NULL, NULL),
                                                                                                                     (43, 'Ciudad del Vaticano', 'Vatican City State', 'VA', 'VAT', '39', NULL, NULL),
                                                                                                                     (44, 'Colombia', 'Colombia', 'CO', 'COL', '57', NULL, NULL),
                                                                                                                     (45, 'Comoras', 'Comoros', 'KM', 'COM', '269', NULL, NULL),
                                                                                                                     (46, 'República del Congo', 'Republic of the Cong', 'CG', 'COG', '242', NULL, NULL),
                                                                                                                     (47, 'República Democrátic', 'Democratic Republic ', 'CD', 'COD', '243', NULL, NULL),
                                                                                                                     (48, 'Corea del Norte', 'North Korea', 'KP', 'PRK', '850', NULL, NULL),
                                                                                                                     (49, 'Corea del Sur', 'South Korea', 'KR', 'KOR', '82', NULL, NULL),
                                                                                                                     (50, 'Costa de Marfil', 'Ivory Coast', 'CI', 'CIV', '225', NULL, NULL),
                                                                                                                     (51, 'Costa Rica', 'Costa Rica', 'CR', 'CRI', '506', NULL, NULL),
                                                                                                                     (52, 'Croacia', 'Croatia', 'HR', 'HRV', '385', NULL, NULL),
                                                                                                                     (53, 'Cuba', 'Cuba', 'CU', 'CUB', '53', NULL, NULL),
                                                                                                                     (54, 'Curazao', 'Curaçao', 'CW', 'CWU', '5999', NULL, NULL),
                                                                                                                     (55, 'Dinamarca', 'Denmark', 'DK', 'DNK', '45', NULL, NULL),
                                                                                                                     (56, 'Dominica', 'Dominica', 'DM', 'DMA', '1 76', NULL, NULL),
                                                                                                                     (57, 'Ecuador', 'Ecuador', 'EC', 'ECU', '593', NULL, NULL),
                                                                                                                     (58, 'Egipto', 'Egypt', 'EG', 'EGY', '20', NULL, NULL),
                                                                                                                     (59, 'El Salvador', 'El Salvador', 'SV', 'SLV', '503', NULL, NULL),
                                                                                                                     (60, 'Emiratos Árabes Unid', 'United Arab Emirates', 'AE', 'ARE', '971', NULL, NULL),
                                                                                                                     (61, 'Eritrea', 'Eritrea', 'ER', 'ERI', '291', NULL, NULL),
                                                                                                                     (62, 'Eslovaquia', 'Slovakia', 'SK', 'SVK', '421', NULL, NULL),
                                                                                                                     (63, 'Eslovenia', 'Slovenia', 'SI', 'SVN', '386', NULL, NULL),
                                                                                                                     (64, 'España', 'Spain', 'ES', 'ESP', '34', NULL, NULL),
                                                                                                                     (65, 'Estados Unidos de Am', 'United States of Ame', 'US', 'USA', '1', NULL, NULL),
                                                                                                                     (66, 'Estonia', 'Estonia', 'EE', 'EST', '372', NULL, NULL),
                                                                                                                     (67, 'Etiopía', 'Ethiopia', 'ET', 'ETH', '251', NULL, NULL),
                                                                                                                     (68, 'Filipinas', 'Philippines', 'PH', 'PHL', '63', NULL, NULL),
                                                                                                                     (69, 'Finlandia', 'Finland', 'FI', 'FIN', '358', NULL, NULL),
                                                                                                                     (70, 'Fiyi', 'Fiji', 'FJ', 'FJI', '679', NULL, NULL),
                                                                                                                     (71, 'Francia', 'France', 'FR', 'FRA', '33', NULL, NULL),
                                                                                                                     (72, 'Gabón', 'Gabon', 'GA', 'GAB', '241', NULL, NULL),
                                                                                                                     (73, 'Gambia', 'Gambia', 'GM', 'GMB', '220', NULL, NULL),
                                                                                                                     (74, 'Georgia', 'Georgia', 'GE', 'GEO', '995', NULL, NULL),
                                                                                                                     (75, 'Ghana', 'Ghana', 'GH', 'GHA', '233', NULL, NULL),
                                                                                                                     (76, 'Gibraltar', 'Gibraltar', 'GI', 'GIB', '350', NULL, NULL),
                                                                                                                     (77, 'Granada', 'Grenada', 'GD', 'GRD', '1 47', NULL, NULL),
                                                                                                                     (78, 'Grecia', 'Greece', 'GR', 'GRC', '30', NULL, NULL),
                                                                                                                     (79, 'Groenlandia', 'Greenland', 'GL', 'GRL', '299', NULL, NULL),
                                                                                                                     (80, 'Guadalupe', 'Guadeloupe', 'GP', 'GLP', '590', NULL, NULL),
                                                                                                                     (81, 'Guam', 'Guam', 'GU', 'GUM', '1 67', NULL, NULL),
                                                                                                                     (82, 'Guatemala', 'Guatemala', 'GT', 'GTM', '502', NULL, NULL),
                                                                                                                     (83, 'Guayana Francesa', 'French Guiana', 'GF', 'GUF', '594', NULL, NULL),
                                                                                                                     (84, 'Guernsey', 'Guernsey', 'GG', 'GGY', '44', NULL, NULL),
                                                                                                                     (85, 'Guinea', 'Guinea', 'GN', 'GIN', '224', NULL, NULL),
                                                                                                                     (86, 'Guinea Ecuatorial', 'Equatorial Guinea', 'GQ', 'GNQ', '240', NULL, NULL),
                                                                                                                     (87, 'Guinea-Bissau', 'Guinea-Bissau', 'GW', 'GNB', '245', NULL, NULL),
                                                                                                                     (88, 'Guyana', 'Guyana', 'GY', 'GUY', '592', NULL, NULL),
                                                                                                                     (89, 'Haití', 'Haiti', 'HT', 'HTI', '509', NULL, NULL),
                                                                                                                     (90, 'Honduras', 'Honduras', 'HN', 'HND', '504', NULL, NULL),
                                                                                                                     (91, 'Hong kong', 'Hong Kong', 'HK', 'HKG', '852', NULL, NULL),
                                                                                                                     (92, 'Hungría', 'Hungary', 'HU', 'HUN', '36', NULL, NULL),
                                                                                                                     (93, 'India', 'India', 'IN', 'IND', '91', NULL, NULL),
                                                                                                                     (94, 'Indonesia', 'Indonesia', 'ID', 'IDN', '62', NULL, NULL),
                                                                                                                     (95, 'Irán', 'Iran', 'IR', 'IRN', '98', NULL, NULL),
                                                                                                                     (96, 'Irak', 'Iraq', 'IQ', 'IRQ', '964', NULL, NULL),
                                                                                                                     (97, 'Irlanda', 'Ireland', 'IE', 'IRL', '353', NULL, NULL),
                                                                                                                     (98, 'Isla Bouvet', 'Bouvet Island', 'BV', 'BVT', '', NULL, NULL),
                                                                                                                     (99, 'Isla de Man', 'Isle of Man', 'IM', 'IMN', '44', NULL, NULL),
                                                                                                                     (100, 'Isla de Navidad', 'Christmas Island', 'CX', 'CXR', '61', NULL, NULL),
                                                                                                                     (101, 'Isla Norfolk', 'Norfolk Island', 'NF', 'NFK', '672', NULL, NULL),
                                                                                                                     (102, 'Islandia', 'Iceland', 'IS', 'ISL', '354', NULL, NULL),
                                                                                                                     (103, 'Islas Bermudas', 'Bermuda Islands', 'BM', 'BMU', '1 44', NULL, NULL),
                                                                                                                     (104, 'Islas Caimán', 'Cayman Islands', 'KY', 'CYM', '1 34', NULL, NULL),
                                                                                                                     (105, 'Islas Cocos (Keeling', 'Cocos (Keeling) Isla', 'CC', 'CCK', '61', NULL, NULL),
                                                                                                                     (106, 'Islas Cook', 'Cook Islands', 'CK', 'COK', '682', NULL, NULL),
                                                                                                                     (107, 'Islas de Åland', 'Åland Islands', 'AX', 'ALA', '358', NULL, NULL),
                                                                                                                     (108, 'Islas Feroe', 'Faroe Islands', 'FO', 'FRO', '298', NULL, NULL),
                                                                                                                     (109, 'Islas Georgias del S', 'South Georgia and th', 'GS', 'SGS', '500', NULL, NULL),
                                                                                                                     (110, 'Islas Heard y McDona', 'Heard Island and McD', 'HM', 'HMD', '', NULL, NULL),
                                                                                                                     (111, 'Islas Maldivas', 'Maldives', 'MV', 'MDV', '960', NULL, NULL),
                                                                                                                     (112, 'Islas Malvinas', 'Falkland Islands (Ma', 'FK', 'FLK', '500', NULL, NULL),
                                                                                                                     (113, 'Islas Marianas del N', 'Northern Mariana Isl', 'MP', 'MNP', '1 67', NULL, NULL),
                                                                                                                     (114, 'Islas Marshall', 'Marshall Islands', 'MH', 'MHL', '692', NULL, NULL),
                                                                                                                     (115, 'Islas Pitcairn', 'Pitcairn Islands', 'PN', 'PCN', '870', NULL, NULL),
                                                                                                                     (116, 'Islas Salomón', 'Solomon Islands', 'SB', 'SLB', '677', NULL, NULL),
                                                                                                                     (117, 'Islas Turcas y Caico', 'Turks and Caicos Isl', 'TC', 'TCA', '1 64', NULL, NULL),
                                                                                                                     (118, 'Islas Ultramarinas M', 'United States Minor ', 'UM', 'UMI', '246', NULL, NULL),
                                                                                                                     (119, 'Islas Vírgenes Britá', 'Virgin Islands', 'VG', 'VGB', '1 28', NULL, NULL),
                                                                                                                     (120, 'Islas Vírgenes de lo', 'United States Virgin', 'VI', 'VIR', '1 34', NULL, NULL),
                                                                                                                     (121, 'Israel', 'Israel', 'IL', 'ISR', '972', NULL, NULL),
                                                                                                                     (122, 'Italia', 'Italy', 'IT', 'ITA', '39', NULL, NULL),
                                                                                                                     (123, 'Jamaica', 'Jamaica', 'JM', 'JAM', '1 87', NULL, NULL),
                                                                                                                     (124, 'Japón', 'Japan', 'JP', 'JPN', '81', NULL, NULL),
                                                                                                                     (125, 'Jersey', 'Jersey', 'JE', 'JEY', '44', NULL, NULL),
                                                                                                                     (126, 'Jordania', 'Jordan', 'JO', 'JOR', '962', NULL, NULL),
                                                                                                                     (127, 'Kazajistán', 'Kazakhstan', 'KZ', 'KAZ', '7', NULL, NULL),
                                                                                                                     (128, 'Kenia', 'Kenya', 'KE', 'KEN', '254', NULL, NULL),
                                                                                                                     (129, 'Kirguistán', 'Kyrgyzstan', 'KG', 'KGZ', '996', NULL, NULL),
                                                                                                                     (130, 'Kiribati', 'Kiribati', 'KI', 'KIR', '686', NULL, NULL),
                                                                                                                     (131, 'Kuwait', 'Kuwait', 'KW', 'KWT', '965', NULL, NULL),
                                                                                                                     (132, 'Líbano', 'Lebanon', 'LB', 'LBN', '961', NULL, NULL),
                                                                                                                     (133, 'Laos', 'Laos', 'LA', 'LAO', '856', NULL, NULL),
                                                                                                                     (134, 'Lesoto', 'Lesotho', 'LS', 'LSO', '266', NULL, NULL),
                                                                                                                     (135, 'Letonia', 'Latvia', 'LV', 'LVA', '371', NULL, NULL),
                                                                                                                     (136, 'Liberia', 'Liberia', 'LR', 'LBR', '231', NULL, NULL),
                                                                                                                     (137, 'Libia', 'Libya', 'LY', 'LBY', '218', NULL, NULL),
                                                                                                                     (138, 'Liechtenstein', 'Liechtenstein', 'LI', 'LIE', '423', NULL, NULL),
                                                                                                                     (139, 'Lituania', 'Lithuania', 'LT', 'LTU', '370', NULL, NULL),
                                                                                                                     (140, 'Luxemburgo', 'Luxembourg', 'LU', 'LUX', '352', NULL, NULL),
                                                                                                                     (141, 'México', 'Mexico', 'MX', 'MEX', '52', NULL, NULL),
                                                                                                                     (142, 'Mónaco', 'Monaco', 'MC', 'MCO', '377', NULL, NULL),
                                                                                                                     (143, 'Macao', 'Macao', 'MO', 'MAC', '853', NULL, NULL),
                                                                                                                     (144, 'Macedônia', 'Macedonia', 'MK', 'MKD', '389', NULL, NULL),
                                                                                                                     (145, 'Madagascar', 'Madagascar', 'MG', 'MDG', '261', NULL, NULL),
                                                                                                                     (146, 'Malasia', 'Malaysia', 'MY', 'MYS', '60', NULL, NULL),
                                                                                                                     (147, 'Malawi', 'Malawi', 'MW', 'MWI', '265', NULL, NULL),
                                                                                                                     (148, 'Mali', 'Mali', 'ML', 'MLI', '223', NULL, NULL),
                                                                                                                     (149, 'Malta', 'Malta', 'MT', 'MLT', '356', NULL, NULL),
                                                                                                                     (150, 'Marruecos', 'Morocco', 'MA', 'MAR', '212', NULL, NULL),
                                                                                                                     (151, 'Martinica', 'Martinique', 'MQ', 'MTQ', '596', NULL, NULL),
                                                                                                                     (152, 'Mauricio', 'Mauritius', 'MU', 'MUS', '230', NULL, NULL),
                                                                                                                     (153, 'Mauritania', 'Mauritania', 'MR', 'MRT', '222', NULL, NULL),
                                                                                                                     (154, 'Mayotte', 'Mayotte', 'YT', 'MYT', '262', NULL, NULL),
                                                                                                                     (155, 'Micronesia', 'Estados Federados de', 'FM', 'FSM', '691', NULL, NULL),
                                                                                                                     (156, 'Moldavia', 'Moldova', 'MD', 'MDA', '373', NULL, NULL),
                                                                                                                     (157, 'Mongolia', 'Mongolia', 'MN', 'MNG', '976', NULL, NULL),
                                                                                                                     (158, 'Montenegro', 'Montenegro', 'ME', 'MNE', '382', NULL, NULL),
                                                                                                                     (159, 'Montserrat', 'Montserrat', 'MS', 'MSR', '1 66', NULL, NULL),
                                                                                                                     (160, 'Mozambique', 'Mozambique', 'MZ', 'MOZ', '258', NULL, NULL),
                                                                                                                     (161, 'Namibia', 'Namibia', 'NA', 'NAM', '264', NULL, NULL),
                                                                                                                     (162, 'Nauru', 'Nauru', 'NR', 'NRU', '674', NULL, NULL),
                                                                                                                     (163, 'Nepal', 'Nepal', 'NP', 'NPL', '977', NULL, NULL),
                                                                                                                     (164, 'Nicaragua', 'Nicaragua', 'NI', 'NIC', '505', NULL, NULL),
                                                                                                                     (165, 'Niger', 'Niger', 'NE', 'NER', '227', NULL, NULL),
                                                                                                                     (166, 'Nigeria', 'Nigeria', 'NG', 'NGA', '234', NULL, NULL),
                                                                                                                     (167, 'Niue', 'Niue', 'NU', 'NIU', '683', NULL, NULL),
                                                                                                                     (168, 'Noruega', 'Norway', 'NO', 'NOR', '47', NULL, NULL),
                                                                                                                     (169, 'Nueva Caledonia', 'New Caledonia', 'NC', 'NCL', '687', NULL, NULL),
                                                                                                                     (170, 'Nueva Zelanda', 'New Zealand', 'NZ', 'NZL', '64', NULL, NULL),
                                                                                                                     (171, 'Omán', 'Oman', 'OM', 'OMN', '968', NULL, NULL),
                                                                                                                     (172, 'Países Bajos', 'Netherlands', 'NL', 'NLD', '31', NULL, NULL),
                                                                                                                     (173, 'Pakistán', 'Pakistan', 'PK', 'PAK', '92', NULL, NULL),
                                                                                                                     (174, 'Palau', 'Palau', 'PW', 'PLW', '680', NULL, NULL),
                                                                                                                     (175, 'Palestina', 'Palestine', 'PS', 'PSE', '970', NULL, NULL),
                                                                                                                     (176, 'Panamá', 'Panama', 'PA', 'PAN', '507', NULL, NULL),
                                                                                                                     (177, 'Papúa Nueva Guinea', 'Papua New Guinea', 'PG', 'PNG', '675', NULL, NULL),
                                                                                                                     (178, 'Paraguay', 'Paraguay', 'PY', 'PRY', '595', NULL, NULL),
                                                                                                                     (179, 'Perú', 'Peru', 'PE', 'PER', '51', NULL, NULL),
                                                                                                                     (180, 'Polinesia Francesa', 'French Polynesia', 'PF', 'PYF', '689', NULL, NULL),
                                                                                                                     (181, 'Polonia', 'Poland', 'PL', 'POL', '48', NULL, NULL),
                                                                                                                     (182, 'Portugal', 'Portugal', 'PT', 'PRT', '351', NULL, NULL),
                                                                                                                     (183, 'Puerto Rico', 'Puerto Rico', 'PR', 'PRI', '1', NULL, NULL),
                                                                                                                     (184, 'Qatar', 'Qatar', 'QA', 'QAT', '974', NULL, NULL),
                                                                                                                     (185, 'Reino Unido', 'United Kingdom', 'GB', 'GBR', '44', NULL, NULL),
                                                                                                                     (186, 'República Centroafri', 'Central African Repu', 'CF', 'CAF', '236', NULL, NULL),
                                                                                                                     (187, 'República Checa', 'Czech Republic', 'CZ', 'CZE', '420', NULL, NULL),
                                                                                                                     (188, 'República Dominicana', 'Dominican Republic', 'DO', 'DOM', '1 80', NULL, NULL),
                                                                                                                     (189, 'República de Sudán d', 'South Sudan', 'SS', 'SSD', '211', NULL, NULL),
                                                                                                                     (190, 'Reunión', 'Réunion', 'RE', 'REU', '262', NULL, NULL),
                                                                                                                     (191, 'Ruanda', 'Rwanda', 'RW', 'RWA', '250', NULL, NULL),
                                                                                                                     (192, 'Rumanía', 'Romania', 'RO', 'ROU', '40', NULL, NULL),
                                                                                                                     (193, 'Rusia', 'Russia', 'RU', 'RUS', '7', NULL, NULL),
                                                                                                                     (194, 'Sahara Occidental', 'Western Sahara', 'EH', 'ESH', '212', NULL, NULL),
                                                                                                                     (195, 'Samoa', 'Samoa', 'WS', 'WSM', '685', NULL, NULL),
                                                                                                                     (196, 'Samoa Americana', 'American Samoa', 'AS', 'ASM', '1 68', NULL, NULL),
                                                                                                                     (197, 'San Bartolomé', 'Saint Barthélemy', 'BL', 'BLM', '590', NULL, NULL),
                                                                                                                     (198, 'San Cristóbal y Niev', 'Saint Kitts and Nevi', 'KN', 'KNA', '1 86', NULL, NULL),
                                                                                                                     (199, 'San Marino', 'San Marino', 'SM', 'SMR', '378', NULL, NULL),
                                                                                                                     (200, 'San Martín (Francia)', 'Saint Martin (French', 'MF', 'MAF', '1 59', NULL, NULL),
                                                                                                                     (201, 'San Pedro y Miquelón', 'Saint Pierre and Miq', 'PM', 'SPM', '508', NULL, NULL),
                                                                                                                     (202, 'San Vicente y las Gr', 'Saint Vincent and th', 'VC', 'VCT', '1 78', NULL, NULL),
                                                                                                                     (203, 'Santa Elena', 'Ascensión y Tristán ', 'SH', 'SHN', '290', NULL, NULL),
                                                                                                                     (204, 'Santa Lucía', 'Saint Lucia', 'LC', 'LCA', '1 75', NULL, NULL),
                                                                                                                     (205, 'Santo Tomé y Príncip', 'Sao Tome and Princip', 'ST', 'STP', '239', NULL, NULL),
                                                                                                                     (206, 'Senegal', 'Senegal', 'SN', 'SEN', '221', NULL, NULL),
                                                                                                                     (207, 'Serbia', 'Serbia', 'RS', 'SRB', '381', NULL, NULL),
                                                                                                                     (208, 'Seychelles', 'Seychelles', 'SC', 'SYC', '248', NULL, NULL),
                                                                                                                     (209, 'Sierra Leona', 'Sierra Leone', 'SL', 'SLE', '232', NULL, NULL),
                                                                                                                     (210, 'Singapur', 'Singapore', 'SG', 'SGP', '65', NULL, NULL),
                                                                                                                     (211, 'Sint Maarten', 'Sint Maarten', 'SX', 'SMX', '1 72', NULL, NULL),
                                                                                                                     (212, 'Siria', 'Syria', 'SY', 'SYR', '963', NULL, NULL),
                                                                                                                     (213, 'Somalia', 'Somalia', 'SO', 'SOM', '252', NULL, NULL),
                                                                                                                     (214, 'Sri lanka', 'Sri Lanka', 'LK', 'LKA', '94', NULL, NULL),
                                                                                                                     (215, 'Sudáfrica', 'South Africa', 'ZA', 'ZAF', '27', NULL, NULL),
                                                                                                                     (216, 'Sudán', 'Sudan', 'SD', 'SDN', '249', NULL, NULL),
                                                                                                                     (217, 'Suecia', 'Sweden', 'SE', 'SWE', '46', NULL, NULL),
                                                                                                                     (218, 'Suiza', 'Switzerland', 'CH', 'CHE', '41', NULL, NULL),
                                                                                                                     (219, 'Surinám', 'Suriname', 'SR', 'SUR', '597', NULL, NULL),
                                                                                                                     (220, 'Svalbard y Jan Mayen', 'Svalbard and Jan May', 'SJ', 'SJM', '47', NULL, NULL),
                                                                                                                     (221, 'Swazilandia', 'Swaziland', 'SZ', 'SWZ', '268', NULL, NULL),
                                                                                                                     (222, 'Tayikistán', 'Tajikistan', 'TJ', 'TJK', '992', NULL, NULL),
                                                                                                                     (223, 'Tailandia', 'Thailand', 'TH', 'THA', '66', NULL, NULL),
                                                                                                                     (224, 'Taiwán', 'Taiwan', 'TW', 'TWN', '886', NULL, NULL),
                                                                                                                     (225, 'Tanzania', 'Tanzania', 'TZ', 'TZA', '255', NULL, NULL),
                                                                                                                     (226, 'Territorio Británico', 'British Indian Ocean', 'IO', 'IOT', '246', NULL, NULL),
                                                                                                                     (227, 'Territorios Australe', 'French Southern Terr', 'TF', 'ATF', '', NULL, NULL),
                                                                                                                     (228, 'Timor Oriental', 'East Timor', 'TL', 'TLS', '670', NULL, NULL),
                                                                                                                     (229, 'Togo', 'Togo', 'TG', 'TGO', '228', NULL, NULL),
                                                                                                                     (230, 'Tokelau', 'Tokelau', 'TK', 'TKL', '690', NULL, NULL),
                                                                                                                     (231, 'Tonga', 'Tonga', 'TO', 'TON', '676', NULL, NULL),
                                                                                                                     (232, 'Trinidad y Tobago', 'Trinidad and Tobago', 'TT', 'TTO', '1 86', NULL, NULL),
                                                                                                                     (233, 'Tunez', 'Tunisia', 'TN', 'TUN', '216', NULL, NULL),
                                                                                                                     (234, 'Turkmenistán', 'Turkmenistan', 'TM', 'TKM', '993', NULL, NULL),
                                                                                                                     (235, 'Turquía', 'Turkey', 'TR', 'TUR', '90', NULL, NULL),
                                                                                                                     (236, 'Tuvalu', 'Tuvalu', 'TV', 'TUV', '688', NULL, NULL),
                                                                                                                     (237, 'Ucrania', 'Ukraine', 'UA', 'UKR', '380', NULL, NULL),
                                                                                                                     (238, 'Uganda', 'Uganda', 'UG', 'UGA', '256', NULL, NULL),
                                                                                                                     (239, 'Uruguay', 'Uruguay', 'UY', 'URY', '598', NULL, NULL),
                                                                                                                     (240, 'Uzbekistán', 'Uzbekistan', 'UZ', 'UZB', '998', NULL, NULL),
                                                                                                                     (241, 'Vanuatu', 'Vanuatu', 'VU', 'VUT', '678', NULL, NULL),
                                                                                                                     (242, 'Venezuela', 'Venezuela', 'VE', 'VEN', '58', NULL, NULL),
                                                                                                                     (243, 'Vietnam', 'Vietnam', 'VN', 'VNM', '84', NULL, NULL),
                                                                                                                     (244, 'Wallis y Futuna', 'Wallis and Futuna', 'WF', 'WLF', '681', NULL, NULL),
                                                                                                                     (245, 'Yemen', 'Yemen', 'YE', 'YEM', '967', NULL, NULL),
                                                                                                                     (246, 'Yibuti', 'Djibouti', 'DJ', 'DJI', '253', NULL, NULL),
                                                                                                                     (247, 'Zambia', 'Zambia', 'ZM', 'ZMB', '260', NULL, NULL),
                                                                                                                     (248, 'Zimbabue', 'Zimbabwe', 'ZW', 'ZWE', '263', NULL, NULL);
